function(_pdf2docx_detect_path var_name)
  foreach(candidate IN LISTS ARGN)
    if(EXISTS "${candidate}/CMakeLists.txt")
      set(${var_name} "${candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${var_name} "" PARENT_SCOPE)
endfunction()

function(_pdf2docx_log_path dep_name dep_path)
  if(dep_path)
    message(STATUS "[deps] ${dep_name}: found at ${dep_path}")
  else()
    message(WARNING "[deps] ${dep_name}: source path not found")
  endif()
endfunction()

function(_pdf2docx_target_version out_var target_name)
  set(version "unknown")
  if(target_name AND TARGET ${target_name})
    get_target_property(target_version ${target_name} VERSION)
    if(target_version AND NOT target_version STREQUAL "target_version-NOTFOUND")
      set(version "${target_version}")
    endif()
  endif()
  set(${out_var} "${version}" PARENT_SCOPE)
endfunction()

function(_pdf2docx_log_dependency dep_name dep_path dep_target dep_version dep_enabled)
  if(dep_enabled)
    if(dep_path)
      set(dep_source "${dep_path}")
    else()
      set(dep_source "<system>")
    endif()
    if(NOT dep_target)
      set(dep_target "<none>")
    endif()
    if(NOT dep_version)
      set(dep_version "unknown")
    endif()
    message(STATUS "[deps] ${dep_name}: source=${dep_source}, target=${dep_target}, version=${dep_version}")
  else()
    message(WARNING "[deps] ${dep_name}: unresolved")
  endif()
endfunction()

function(_pdf2docx_try_link_target out_var)
  foreach(candidate IN LISTS ARGN)
    if(TARGET ${candidate})
      set(${out_var} "${candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${out_var} "" PARENT_SCOPE)
endfunction()

function(_pdf2docx_import_zlib zlib_path use_bundled add_subdir)
  set(PDF2DOCX_ZLIB_VERSION "unknown")
  find_package(ZLIB QUIET)
  if(use_bundled AND add_subdir AND zlib_path AND NOT TARGET ZLIB::ZLIB AND NOT TARGET zlib)
    add_subdirectory("${zlib_path}" "${CMAKE_BINARY_DIR}/_deps/zlib" EXCLUDE_FROM_ALL)
  endif()

  _pdf2docx_try_link_target(PDF2DOCX_ZLIB_TARGET ZLIB::ZLIB zlib zlibstatic)
  if(ZLIB_VERSION_STRING)
    set(PDF2DOCX_ZLIB_VERSION "${ZLIB_VERSION_STRING}")
  endif()
  if(PDF2DOCX_ZLIB_TARGET)
    _pdf2docx_target_version(_zlib_target_version "${PDF2DOCX_ZLIB_TARGET}")
    if(NOT _zlib_target_version STREQUAL "unknown")
      set(PDF2DOCX_ZLIB_VERSION "${_zlib_target_version}")
    endif()
    set(PDF2DOCX_HAS_ZLIB 1 PARENT_SCOPE)
    set(PDF2DOCX_ZLIB_TARGET "${PDF2DOCX_ZLIB_TARGET}" PARENT_SCOPE)
  else()
    set(PDF2DOCX_HAS_ZLIB 0 PARENT_SCOPE)
    set(PDF2DOCX_ZLIB_TARGET "" PARENT_SCOPE)
  endif()
  set(PDF2DOCX_ZLIB_VERSION "${PDF2DOCX_ZLIB_VERSION}" PARENT_SCOPE)
endfunction()

function(_pdf2docx_import_tinyxml2 tinyxml2_path use_bundled add_subdir)
  set(PDF2DOCX_TINYXML2_VERSION "unknown")
  find_package(tinyxml2 QUIET CONFIG)
  if(use_bundled AND add_subdir AND tinyxml2_path AND NOT TARGET tinyxml2::tinyxml2 AND NOT TARGET tinyxml2)
    add_subdirectory("${tinyxml2_path}" "${CMAKE_BINARY_DIR}/_deps/tinyxml2" EXCLUDE_FROM_ALL)
  endif()

  if(tinyxml2_VERSION)
    set(PDF2DOCX_TINYXML2_VERSION "${tinyxml2_VERSION}")
  elseif(tinyxml2_VERSION_STRING)
    set(PDF2DOCX_TINYXML2_VERSION "${tinyxml2_VERSION_STRING}")
  endif()
  _pdf2docx_try_link_target(PDF2DOCX_TINYXML2_TARGET tinyxml2::tinyxml2 tinyxml2)
  if(PDF2DOCX_TINYXML2_TARGET)
    _pdf2docx_target_version(_tinyxml2_target_version "${PDF2DOCX_TINYXML2_TARGET}")
    if(NOT _tinyxml2_target_version STREQUAL "unknown")
      set(PDF2DOCX_TINYXML2_VERSION "${_tinyxml2_target_version}")
    endif()
    set(PDF2DOCX_HAS_TINYXML2 1 PARENT_SCOPE)
    set(PDF2DOCX_TINYXML2_TARGET "${PDF2DOCX_TINYXML2_TARGET}" PARENT_SCOPE)
  else()
    set(PDF2DOCX_HAS_TINYXML2 0 PARENT_SCOPE)
    set(PDF2DOCX_TINYXML2_TARGET "" PARENT_SCOPE)
  endif()
  set(PDF2DOCX_TINYXML2_VERSION "${PDF2DOCX_TINYXML2_VERSION}" PARENT_SCOPE)
endfunction()

function(_pdf2docx_import_minizip minizip_path use_bundled add_subdir)
  set(PDF2DOCX_MINIZIP_VERSION "unknown")
  find_package(minizip QUIET CONFIG)

  if(use_bundled AND add_subdir AND minizip_path AND NOT TARGET MINIZIP::minizip AND NOT TARGET minizip)
    set(MZ_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(MZ_BUILD_UNIT_TESTS OFF CACHE BOOL "" FORCE)
    set(MZ_BUILD_FUZZ_TESTS OFF CACHE BOOL "" FORCE)
    set(MZ_FETCH_LIBS OFF CACHE BOOL "" FORCE)
    set(MZ_FORCE_FETCH_LIBS OFF CACHE BOOL "" FORCE)
    set(MZ_BZIP2 OFF CACHE BOOL "" FORCE)
    set(MZ_LZMA OFF CACHE BOOL "" FORCE)
    set(MZ_ZSTD OFF CACHE BOOL "" FORCE)
    set(MZ_OPENSSL OFF CACHE BOOL "" FORCE)
    add_subdirectory("${minizip_path}" "${CMAKE_BINARY_DIR}/_deps/minizip-ng" EXCLUDE_FROM_ALL)
  endif()

  if(MZ_VERSION)
    set(PDF2DOCX_MINIZIP_VERSION "${MZ_VERSION}")
  endif()
  _pdf2docx_try_link_target(PDF2DOCX_MINIZIP_TARGET MINIZIP::minizip minizip minizip-ng)
  if(PDF2DOCX_MINIZIP_TARGET)
    _pdf2docx_target_version(_minizip_target_version "${PDF2DOCX_MINIZIP_TARGET}")
    if(NOT _minizip_target_version STREQUAL "unknown")
      set(PDF2DOCX_MINIZIP_VERSION "${_minizip_target_version}")
    endif()
    set(PDF2DOCX_HAS_MINIZIP 1 PARENT_SCOPE)
    set(PDF2DOCX_MINIZIP_TARGET "${PDF2DOCX_MINIZIP_TARGET}" PARENT_SCOPE)
  else()
    set(PDF2DOCX_HAS_MINIZIP 0 PARENT_SCOPE)
    set(PDF2DOCX_MINIZIP_TARGET "" PARENT_SCOPE)
  endif()
  set(PDF2DOCX_MINIZIP_VERSION "${PDF2DOCX_MINIZIP_VERSION}" PARENT_SCOPE)
endfunction()

function(_pdf2docx_import_freetype freetype_path use_bundled add_subdir)
  set(PDF2DOCX_FREETYPE_VERSION "unknown")
  find_package(Freetype QUIET)
  if(use_bundled AND add_subdir AND freetype_path AND NOT TARGET Freetype::Freetype AND NOT TARGET freetype)
    add_subdirectory("${freetype_path}" "${CMAKE_BINARY_DIR}/_deps/freetype2" EXCLUDE_FROM_ALL)
  endif()

  if(FREETYPE_VERSION_STRING)
    set(PDF2DOCX_FREETYPE_VERSION "${FREETYPE_VERSION_STRING}")
  endif()
  _pdf2docx_try_link_target(PDF2DOCX_FREETYPE_TARGET Freetype::Freetype freetype-interface freetype)
  if(PDF2DOCX_FREETYPE_TARGET)
    _pdf2docx_target_version(_freetype_target_version "${PDF2DOCX_FREETYPE_TARGET}")
    if(NOT _freetype_target_version STREQUAL "unknown")
      set(PDF2DOCX_FREETYPE_VERSION "${_freetype_target_version}")
    endif()
    set(PDF2DOCX_HAS_FREETYPE 1 PARENT_SCOPE)
    set(PDF2DOCX_FREETYPE_TARGET "${PDF2DOCX_FREETYPE_TARGET}" PARENT_SCOPE)
  else()
    set(PDF2DOCX_HAS_FREETYPE 0 PARENT_SCOPE)
    set(PDF2DOCX_FREETYPE_TARGET "" PARENT_SCOPE)
  endif()
  set(PDF2DOCX_FREETYPE_VERSION "${PDF2DOCX_FREETYPE_VERSION}" PARENT_SCOPE)
endfunction()

function(_pdf2docx_import_podofo podofo_path use_bundled add_subdir)
  set(PDF2DOCX_PODOFO_VERSION "unknown")
  find_package(podofo QUIET CONFIG)
  if(use_bundled AND add_subdir AND podofo_path AND NOT TARGET podofo::podofo)
    set(PODOFO_BUILD_LIB_ONLY TRUE CACHE BOOL "" FORCE)
    set(PODOFO_BUILD_TEST FALSE CACHE BOOL "" FORCE)
    set(PODOFO_BUILD_EXAMPLES FALSE CACHE BOOL "" FORCE)
    set(PODOFO_BUILD_UNSUPPORTED_TOOLS FALSE CACHE BOOL "" FORCE)
    set(PODOFO_BUILD_STATIC TRUE CACHE BOOL "" FORCE)
    add_subdirectory("${podofo_path}" "${CMAKE_BINARY_DIR}/_deps/podofo" EXCLUDE_FROM_ALL)
  endif()

  if(podofo_VERSION)
    set(PDF2DOCX_PODOFO_VERSION "${podofo_VERSION}")
  elseif(PODOFO_VERSION)
    set(PDF2DOCX_PODOFO_VERSION "${PODOFO_VERSION}")
  endif()
  _pdf2docx_try_link_target(PDF2DOCX_PODOFO_TARGET podofo::podofo podofo_shared podofo_static)
  if(PDF2DOCX_PODOFO_TARGET)
    _pdf2docx_target_version(_podofo_target_version "${PDF2DOCX_PODOFO_TARGET}")
    if(NOT _podofo_target_version STREQUAL "unknown")
      set(PDF2DOCX_PODOFO_VERSION "${_podofo_target_version}")
    endif()
    set(PDF2DOCX_HAS_PODOFO 1 PARENT_SCOPE)
    set(PDF2DOCX_PODOFO_TARGET "${PDF2DOCX_PODOFO_TARGET}" PARENT_SCOPE)
  else()
    set(PDF2DOCX_HAS_PODOFO 0 PARENT_SCOPE)
    set(PDF2DOCX_PODOFO_TARGET "" PARENT_SCOPE)
  endif()
  set(PDF2DOCX_PODOFO_VERSION "${PDF2DOCX_PODOFO_VERSION}" PARENT_SCOPE)
endfunction()

function(pdf2docx_import_dependencies thirdparty_root use_bundled add_subdir strict_deps)
  _pdf2docx_detect_path(PDF2DOCX_PATH_ZLIB
    "${thirdparty_root}/zlib")
  _pdf2docx_detect_path(PDF2DOCX_PATH_TINYXML2
    "${thirdparty_root}/tinyxml2")
  _pdf2docx_detect_path(PDF2DOCX_PATH_MINIZIP
    "${thirdparty_root}/minizip-ng")
  _pdf2docx_detect_path(PDF2DOCX_PATH_FREETYPE
    "${thirdparty_root}/freetype2"
    "${thirdparty_root}/freetype")
  _pdf2docx_detect_path(PDF2DOCX_PATH_PODOFO
    "${thirdparty_root}/podofo")

  _pdf2docx_log_path(zlib "${PDF2DOCX_PATH_ZLIB}")
  _pdf2docx_log_path(tinyxml2 "${PDF2DOCX_PATH_TINYXML2}")
  _pdf2docx_log_path(minizip-ng "${PDF2DOCX_PATH_MINIZIP}")
  _pdf2docx_log_path(freetype2 "${PDF2DOCX_PATH_FREETYPE}")
  _pdf2docx_log_path(podofo "${PDF2DOCX_PATH_PODOFO}")

  _pdf2docx_import_zlib("${PDF2DOCX_PATH_ZLIB}" ${use_bundled} ${add_subdir})
  _pdf2docx_import_tinyxml2("${PDF2DOCX_PATH_TINYXML2}" ${use_bundled} ${add_subdir})
  _pdf2docx_import_minizip("${PDF2DOCX_PATH_MINIZIP}" ${use_bundled} ${add_subdir})
  _pdf2docx_import_freetype("${PDF2DOCX_PATH_FREETYPE}" ${use_bundled} ${add_subdir})
  _pdf2docx_import_podofo("${PDF2DOCX_PATH_PODOFO}" ${use_bundled} ${add_subdir})

  set(PDF2DOCX_HAS_ZLIB ${PDF2DOCX_HAS_ZLIB} PARENT_SCOPE)
  set(PDF2DOCX_HAS_TINYXML2 ${PDF2DOCX_HAS_TINYXML2} PARENT_SCOPE)
  set(PDF2DOCX_HAS_MINIZIP ${PDF2DOCX_HAS_MINIZIP} PARENT_SCOPE)
  set(PDF2DOCX_HAS_FREETYPE ${PDF2DOCX_HAS_FREETYPE} PARENT_SCOPE)
  set(PDF2DOCX_HAS_PODOFO ${PDF2DOCX_HAS_PODOFO} PARENT_SCOPE)

  set(PDF2DOCX_ZLIB_TARGET "${PDF2DOCX_ZLIB_TARGET}" PARENT_SCOPE)
  set(PDF2DOCX_TINYXML2_TARGET "${PDF2DOCX_TINYXML2_TARGET}" PARENT_SCOPE)
  set(PDF2DOCX_MINIZIP_TARGET "${PDF2DOCX_MINIZIP_TARGET}" PARENT_SCOPE)
  set(PDF2DOCX_FREETYPE_TARGET "${PDF2DOCX_FREETYPE_TARGET}" PARENT_SCOPE)
  set(PDF2DOCX_PODOFO_TARGET "${PDF2DOCX_PODOFO_TARGET}" PARENT_SCOPE)

  set(PDF2DOCX_ZLIB_VERSION "${PDF2DOCX_ZLIB_VERSION}" PARENT_SCOPE)
  set(PDF2DOCX_TINYXML2_VERSION "${PDF2DOCX_TINYXML2_VERSION}" PARENT_SCOPE)
  set(PDF2DOCX_MINIZIP_VERSION "${PDF2DOCX_MINIZIP_VERSION}" PARENT_SCOPE)
  set(PDF2DOCX_FREETYPE_VERSION "${PDF2DOCX_FREETYPE_VERSION}" PARENT_SCOPE)
  set(PDF2DOCX_PODOFO_VERSION "${PDF2DOCX_PODOFO_VERSION}" PARENT_SCOPE)

  _pdf2docx_log_dependency("zlib" "${PDF2DOCX_PATH_ZLIB}" "${PDF2DOCX_ZLIB_TARGET}" "${PDF2DOCX_ZLIB_VERSION}" ${PDF2DOCX_HAS_ZLIB})
  _pdf2docx_log_dependency("tinyxml2" "${PDF2DOCX_PATH_TINYXML2}" "${PDF2DOCX_TINYXML2_TARGET}" "${PDF2DOCX_TINYXML2_VERSION}" ${PDF2DOCX_HAS_TINYXML2})
  _pdf2docx_log_dependency("minizip-ng" "${PDF2DOCX_PATH_MINIZIP}" "${PDF2DOCX_MINIZIP_TARGET}" "${PDF2DOCX_MINIZIP_VERSION}" ${PDF2DOCX_HAS_MINIZIP})
  _pdf2docx_log_dependency("freetype2" "${PDF2DOCX_PATH_FREETYPE}" "${PDF2DOCX_FREETYPE_TARGET}" "${PDF2DOCX_FREETYPE_VERSION}" ${PDF2DOCX_HAS_FREETYPE})
  _pdf2docx_log_dependency("podofo" "${PDF2DOCX_PATH_PODOFO}" "${PDF2DOCX_PODOFO_TARGET}" "${PDF2DOCX_PODOFO_VERSION}" ${PDF2DOCX_HAS_PODOFO})

  if(strict_deps)
    set(_missing_deps "")
    if(NOT PDF2DOCX_HAS_ZLIB)
      list(APPEND _missing_deps "zlib")
    endif()
    if(NOT PDF2DOCX_HAS_TINYXML2)
      list(APPEND _missing_deps "tinyxml2")
    endif()
    if(NOT PDF2DOCX_HAS_MINIZIP)
      list(APPEND _missing_deps "minizip-ng")
    endif()
    if(NOT PDF2DOCX_HAS_FREETYPE)
      list(APPEND _missing_deps "freetype2")
    endif()
    if(NOT PDF2DOCX_HAS_PODOFO)
      list(APPEND _missing_deps "podofo")
    endif()
    if(_missing_deps)
      string(REPLACE ";" ", " _missing_deps_csv "${_missing_deps}")
      message(FATAL_ERROR "[deps] strict mode enabled, missing: ${_missing_deps_csv}")
    endif()
  endif()

  message(STATUS "[deps] resolved: zlib=${PDF2DOCX_HAS_ZLIB}, tinyxml2=${PDF2DOCX_HAS_TINYXML2}, minizip=${PDF2DOCX_HAS_MINIZIP}, freetype=${PDF2DOCX_HAS_FREETYPE}, podofo=${PDF2DOCX_HAS_PODOFO}, strict=${strict_deps}")
endfunction()
