function(_pdf2docx_detect_path var_name)
  foreach(candidate IN LISTS ARGN)
    if(EXISTS "${candidate}/CMakeLists.txt")
      set(${var_name} "${candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${var_name} "" PARENT_SCOPE)
endfunction()

function(_pdf2docx_log_path dep_name dep_path)
  if(dep_path)
    message(STATUS "[deps] ${dep_name}: found at ${dep_path}")
  else()
    message(WARNING "[deps] ${dep_name}: source path not found")
  endif()
endfunction()

function(_pdf2docx_try_link_target out_var)
  foreach(candidate IN LISTS ARGN)
    if(TARGET ${candidate})
      set(${out_var} "${candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${out_var} "" PARENT_SCOPE)
endfunction()

function(_pdf2docx_import_zlib zlib_path use_bundled add_subdir)
  find_package(ZLIB QUIET)
  if(use_bundled AND add_subdir AND zlib_path AND NOT TARGET ZLIB::ZLIB AND NOT TARGET zlib)
    add_subdirectory("${zlib_path}" "${CMAKE_BINARY_DIR}/_deps/zlib" EXCLUDE_FROM_ALL)
  endif()

  _pdf2docx_try_link_target(PDF2DOCX_ZLIB_TARGET ZLIB::ZLIB zlib zlibstatic)
  if(PDF2DOCX_ZLIB_TARGET)
    set(PDF2DOCX_HAS_ZLIB 1 PARENT_SCOPE)
    set(PDF2DOCX_ZLIB_TARGET "${PDF2DOCX_ZLIB_TARGET}" PARENT_SCOPE)
  else()
    set(PDF2DOCX_HAS_ZLIB 0 PARENT_SCOPE)
    set(PDF2DOCX_ZLIB_TARGET "" PARENT_SCOPE)
  endif()
endfunction()

function(_pdf2docx_import_tinyxml2 tinyxml2_path use_bundled add_subdir)
  find_package(tinyxml2 QUIET CONFIG)
  if(use_bundled AND add_subdir AND tinyxml2_path AND NOT TARGET tinyxml2::tinyxml2 AND NOT TARGET tinyxml2)
    add_subdirectory("${tinyxml2_path}" "${CMAKE_BINARY_DIR}/_deps/tinyxml2" EXCLUDE_FROM_ALL)
  endif()

  _pdf2docx_try_link_target(PDF2DOCX_TINYXML2_TARGET tinyxml2::tinyxml2 tinyxml2)
  if(PDF2DOCX_TINYXML2_TARGET)
    set(PDF2DOCX_HAS_TINYXML2 1 PARENT_SCOPE)
    set(PDF2DOCX_TINYXML2_TARGET "${PDF2DOCX_TINYXML2_TARGET}" PARENT_SCOPE)
  else()
    set(PDF2DOCX_HAS_TINYXML2 0 PARENT_SCOPE)
    set(PDF2DOCX_TINYXML2_TARGET "" PARENT_SCOPE)
  endif()
endfunction()

function(_pdf2docx_import_minizip minizip_path use_bundled add_subdir)
  find_package(minizip QUIET CONFIG)

  if(use_bundled AND add_subdir AND minizip_path AND NOT TARGET MINIZIP::minizip AND NOT TARGET minizip)
    set(MZ_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(MZ_BUILD_UNIT_TESTS OFF CACHE BOOL "" FORCE)
    set(MZ_BUILD_FUZZ_TESTS OFF CACHE BOOL "" FORCE)
    set(MZ_FETCH_LIBS OFF CACHE BOOL "" FORCE)
    set(MZ_FORCE_FETCH_LIBS OFF CACHE BOOL "" FORCE)
    set(MZ_BZIP2 OFF CACHE BOOL "" FORCE)
    set(MZ_LZMA OFF CACHE BOOL "" FORCE)
    set(MZ_ZSTD OFF CACHE BOOL "" FORCE)
    set(MZ_OPENSSL OFF CACHE BOOL "" FORCE)
    add_subdirectory("${minizip_path}" "${CMAKE_BINARY_DIR}/_deps/minizip-ng" EXCLUDE_FROM_ALL)
  endif()

  _pdf2docx_try_link_target(PDF2DOCX_MINIZIP_TARGET MINIZIP::minizip minizip minizip-ng)
  if(PDF2DOCX_MINIZIP_TARGET)
    set(PDF2DOCX_HAS_MINIZIP 1 PARENT_SCOPE)
    set(PDF2DOCX_MINIZIP_TARGET "${PDF2DOCX_MINIZIP_TARGET}" PARENT_SCOPE)
  else()
    set(PDF2DOCX_HAS_MINIZIP 0 PARENT_SCOPE)
    set(PDF2DOCX_MINIZIP_TARGET "" PARENT_SCOPE)
  endif()
endfunction()

function(_pdf2docx_import_freetype freetype_path use_bundled add_subdir)
  find_package(Freetype QUIET)
  if(use_bundled AND add_subdir AND freetype_path AND NOT TARGET Freetype::Freetype AND NOT TARGET freetype)
    add_subdirectory("${freetype_path}" "${CMAKE_BINARY_DIR}/_deps/freetype2" EXCLUDE_FROM_ALL)
  endif()

  _pdf2docx_try_link_target(PDF2DOCX_FREETYPE_TARGET Freetype::Freetype freetype-interface freetype)
  if(PDF2DOCX_FREETYPE_TARGET)
    set(PDF2DOCX_HAS_FREETYPE 1 PARENT_SCOPE)
    set(PDF2DOCX_FREETYPE_TARGET "${PDF2DOCX_FREETYPE_TARGET}" PARENT_SCOPE)
  else()
    set(PDF2DOCX_HAS_FREETYPE 0 PARENT_SCOPE)
    set(PDF2DOCX_FREETYPE_TARGET "" PARENT_SCOPE)
  endif()
endfunction()

function(_pdf2docx_import_podofo podofo_path use_bundled add_subdir)
  find_package(podofo QUIET CONFIG)
  if(use_bundled AND add_subdir AND podofo_path AND NOT TARGET podofo::podofo)
    set(PODOFO_BUILD_LIB_ONLY TRUE CACHE BOOL "" FORCE)
    set(PODOFO_BUILD_TEST FALSE CACHE BOOL "" FORCE)
    set(PODOFO_BUILD_EXAMPLES FALSE CACHE BOOL "" FORCE)
    set(PODOFO_BUILD_UNSUPPORTED_TOOLS FALSE CACHE BOOL "" FORCE)
    set(PODOFO_BUILD_STATIC TRUE CACHE BOOL "" FORCE)
    add_subdirectory("${podofo_path}" "${CMAKE_BINARY_DIR}/_deps/podofo" EXCLUDE_FROM_ALL)
  endif()

  _pdf2docx_try_link_target(PDF2DOCX_PODOFO_TARGET podofo::podofo podofo_shared podofo_static)
  if(PDF2DOCX_PODOFO_TARGET)
    set(PDF2DOCX_HAS_PODOFO 1 PARENT_SCOPE)
    set(PDF2DOCX_PODOFO_TARGET "${PDF2DOCX_PODOFO_TARGET}" PARENT_SCOPE)
  else()
    set(PDF2DOCX_HAS_PODOFO 0 PARENT_SCOPE)
    set(PDF2DOCX_PODOFO_TARGET "" PARENT_SCOPE)
  endif()
endfunction()

function(pdf2docx_import_dependencies thirdparty_root use_bundled add_subdir)
  _pdf2docx_detect_path(PDF2DOCX_PATH_ZLIB
    "${thirdparty_root}/zlib")
  _pdf2docx_detect_path(PDF2DOCX_PATH_TINYXML2
    "${thirdparty_root}/tinyxml2")
  _pdf2docx_detect_path(PDF2DOCX_PATH_MINIZIP
    "${thirdparty_root}/minizip-ng")
  _pdf2docx_detect_path(PDF2DOCX_PATH_FREETYPE
    "${thirdparty_root}/freetype2"
    "${thirdparty_root}/freetype")
  _pdf2docx_detect_path(PDF2DOCX_PATH_PODOFO
    "${thirdparty_root}/podofo")

  _pdf2docx_log_path(zlib "${PDF2DOCX_PATH_ZLIB}")
  _pdf2docx_log_path(tinyxml2 "${PDF2DOCX_PATH_TINYXML2}")
  _pdf2docx_log_path(minizip-ng "${PDF2DOCX_PATH_MINIZIP}")
  _pdf2docx_log_path(freetype2 "${PDF2DOCX_PATH_FREETYPE}")
  _pdf2docx_log_path(podofo "${PDF2DOCX_PATH_PODOFO}")

  _pdf2docx_import_zlib("${PDF2DOCX_PATH_ZLIB}" ${use_bundled} ${add_subdir})
  _pdf2docx_import_tinyxml2("${PDF2DOCX_PATH_TINYXML2}" ${use_bundled} ${add_subdir})
  _pdf2docx_import_minizip("${PDF2DOCX_PATH_MINIZIP}" ${use_bundled} ${add_subdir})
  _pdf2docx_import_freetype("${PDF2DOCX_PATH_FREETYPE}" ${use_bundled} ${add_subdir})
  _pdf2docx_import_podofo("${PDF2DOCX_PATH_PODOFO}" ${use_bundled} ${add_subdir})

  set(PDF2DOCX_HAS_ZLIB ${PDF2DOCX_HAS_ZLIB} PARENT_SCOPE)
  set(PDF2DOCX_HAS_TINYXML2 ${PDF2DOCX_HAS_TINYXML2} PARENT_SCOPE)
  set(PDF2DOCX_HAS_MINIZIP ${PDF2DOCX_HAS_MINIZIP} PARENT_SCOPE)
  set(PDF2DOCX_HAS_FREETYPE ${PDF2DOCX_HAS_FREETYPE} PARENT_SCOPE)
  set(PDF2DOCX_HAS_PODOFO ${PDF2DOCX_HAS_PODOFO} PARENT_SCOPE)

  set(PDF2DOCX_ZLIB_TARGET "${PDF2DOCX_ZLIB_TARGET}" PARENT_SCOPE)
  set(PDF2DOCX_TINYXML2_TARGET "${PDF2DOCX_TINYXML2_TARGET}" PARENT_SCOPE)
  set(PDF2DOCX_MINIZIP_TARGET "${PDF2DOCX_MINIZIP_TARGET}" PARENT_SCOPE)
  set(PDF2DOCX_FREETYPE_TARGET "${PDF2DOCX_FREETYPE_TARGET}" PARENT_SCOPE)
  set(PDF2DOCX_PODOFO_TARGET "${PDF2DOCX_PODOFO_TARGET}" PARENT_SCOPE)

  message(STATUS "[deps] resolved: zlib=${PDF2DOCX_HAS_ZLIB}, tinyxml2=${PDF2DOCX_HAS_TINYXML2}, minizip=${PDF2DOCX_HAS_MINIZIP}, freetype=${PDF2DOCX_HAS_FREETYPE}, podofo=${PDF2DOCX_HAS_PODOFO}")
endfunction()
